#!/bin/bash

IMAGE=${2:-"hdd.img"}
LOOP=loop1000

usage() {
    echo -e "Usage: $(basename $0) <option> [image location]\n"
    echo -e "\t--lo\n"
    echo -e "\t--dlo\n"
    echo -e "\t--mnt\n"
    echo -e "\t--umnt\n"
    exit -1
}

if [ $# -lt 1 ]; then
    usage
fi

case $1 in
--lo)
    sudo losetup -d /dev/${LOOP} 2>/dev/null # detach, if already in use
    sudo losetup -P /dev/${LOOP} $IMAGE
    ;;
--dlo)
    sudo losetup -d /dev/${LOOP}
    ;;
--mnt)
    sudo mkdir -p /mnt/${LOOP}/p{1..4} &&
        sudo mount /dev/${LOOP}p1 /mnt/${LOOP}/p1 &&
        sudo mount /dev/${LOOP}p2 /mnt/${LOOP}/p2 &&
        sudo mount /dev/${LOOP}p3 /mnt/${LOOP}/p3 &&
        sudo mount /dev/${LOOP}p4 /mnt/${LOOP}/p4
    ;;
--umnt)
    sudo umount /dev/${LOOP}p4 &&
        sudo umount /dev/${LOOP}p3 &&
        sudo umount /dev/${LOOP}p2 &&
        sudo umount /dev/${LOOP}p1 &&
        sudo rmdir /mnt/${LOOP}/p{1..4} &&
        sudo rmdir /mnt/${LOOP}/
    ;;
*)
    usage
    ;;
esac
